import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mentorada Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Sistema de auxílio à empregabilidade de adultos em transição de carreira para tecnologia
        </h1>

        <p className={styles.description}>
          Projeto por Caio Silva Teixeira
        </p>

        <a href='https://mentorada.vercel.app' target='_blank' rel="noreferrer">
          <div className={styles.card}>
            <h2><u>Acessar projeto &rarr;</u></h2>
            <Image src='/public/mentorada.png' width={600} height={300}/>
          </div>
        </a>

            <br />
            <a href='https://github.com/caioteixeiraa/tcc-front' target='_blank' rel="noreferrer">
              <u>Repositório front-end</u>
            </a>
            <br />
            <a href='https://github.com/caioteixeiraa/abramov' target='_blank' rel="noreferrer">
              <u>Repositório back-end</u>
            </a>
            <br />

          <div className={styles.card}>
            <h2>Motivação</h2>
            <p>&emsp; A taxa de desemprego no Brasil atingiu, segundo o IBGE, no mês de maio de 2021, a marca de 14,7%, consequentemente, 14,8 milhões de brasileiros e brasileiras estão desempregados, sendo que 6 milhões desistiram de procurar uma oportunidade. Enquanto isso, no setor de tecnologia em São Paulo, vem aumentando o número de vagas. Segundo levantamento feito pela plataforma Catho, as vagas para cientista de dados cresceram 671% e para pessoa desenvolvedora web, 97%, por exemplo. 
              <br />&emsp; Por mais que escolas e cursos estão abrindo oportunidades para muitas pessoas começarem seus estudos na área de tecnologia, uma relevante parcela dos estudantes, ainda assim, não conseguem se empregar por ser um mercado competitivo. Tantas pessoas diversas com diferentes experiências e vivências poderiam fazer parte dessa área e contribuir positivamente, segundo estudo da McKinsey, mas falta um suporte nessa etapa final ao buscar um emprego em tecnologia e ajudar essas pessoas em transição de carreira conquistarem seu objetivo.
            </p>
          </div>

          <div className={styles.card}>
            <h2>Objetivo</h2>
            <p>&emsp; O objetivo deste projeto é desenvolver uma solução que auxilie pessoas adultas em transição de carreira para tecnologia a serem empregadas em uma profissão que envolva algum tipo de desenvolvimento de software; entender os problemas e dores que tais pessoas têm para entrar no mercado de trabalho; testar e validar se a solução tem algum impacto positivo na contratação de pessoas desenvolvedoras de software.
	            <br />&emsp; Ao desenvolver a aplicação, espera-se ajudar cada vez mais pessoas a conquistarem uma oportunidade no mercado de tecnologia, uma vez que os profissionais nessa área são extremamente valorizados e possibilitando uma melhora econômica significativa na vida delas.
            </p>
          </div>

          <div className={styles.card}>
            <h2>Metodologia</h2>
            <p>&emsp; Como método de desenvolvimento de projeto, é utilizado o modelo do Diamante Duplo. Ele consiste de duas macro-etapas de divergência-convergência. Cada diamante possui uma etapa de divergência e uma de convergência em seguida.
              <br />&emsp; O primeiro diamante serve para que as pessoas envolvidas no projeto tenham um bom entendimento do problema evitando assumir hipóteses que podem estar enviesadas. Ele é dividido em duas etapas: a de descoberta, que envolve conversar com usuários, dedicar tempo a ferramentas de pesquisa, entrevistas e observações sobre o usuário que você quer resolver os problemas; e a de definição do problema, onde é importante focar em um desafio que o time deseje resolver para que a entrega de valor seja mais efetiva.
              <br />&emsp; Já no segundo diamante, inicia-se o desenvolvimento da solução que possivelmente resolverá o desafio que foi definido no diamante anterior. Ele também é dividido em duas etapas: a de desenvolvimento, onde diversas soluções são consideradas e podem ser geradas a partir de qualquer ferramenta de geração de ideias como brainstormings, por exemplo; e a de entrega, onde se itera sobre o produto em pequena escala, testando e rejeitando as funcionalidades que não funcionam, e/ou melhorando as que funcionam, de maneira rápida.
            </p>
          </div>

          <div className={styles.card}>
            <h2>O sistema</h2>
            <p>
              &emsp;A partir dos resultados obtidos pelas pesquisas feitas nas etapas anteriores do desenvolvimento do projeto, a solução definida para resolver as dores de empregabilidade de pessoas em transição de carreira é um sistema de conexão entre pessoas já empregadas no mercado de trabalho de tecnologia e o público-alvo deste projeto.
              <br />&emsp;O sistema consiste em uma aplicação web em que mentoras(es) e mentoradas(os) podem se cadastrar, criar um perfil listando seus interesses e competências técnicas além do tempo de experiência para pessoas mentoras. Após a criação do perfil, o usuário administrador tem acesso a uma listagens de pessoas mentoras e mentoradas para fazer as conexões. Ao realizar as conexões, os usuários recebem um e-mail para iniciar a conversa entre os dois conectados.
              <br /> &emsp;O sistema segue uma arquitetura uma aplicação front-end construída em Next.js hospedada no Vercel, que se comunica com uma API no back-end implementado em Node.js hospedado no Heroku. API esta que consulta e realiza operações em um banco de dados NoSQL MongoDB.
            </p>
          </div>

          <Image src='/public/arch.png' width={800} height={300}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
